- name: Install jrnl with uv
  command: "uv tool install jrnl"
  # TODO: Make idempotent
  tags:
    - jrnl

- name: Symlink jrnl config file
  file:
    src: "{{ dotfiles_home }}/roles/jrnl/files/jrnl.yaml"
    dest: "{{ dotfiles_user_home}}/.config/jrnl/jrnl.yaml"
    state: link
  tags:
    - jrnl
