
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"


- name: Install Python versions with pyenv
  shell: 'pyenv install {{item}} --skip-existing'
  args:
    creates: "{{ '~/.pyenv/versions/' + item | expanduser }}"
  with_items: '{{pyenv_global_versions}}'
  tags: pyenv

- name: Set global Python versions with pyenv
  copy:
    content: "system\n{% for version in pyenv_global_versions %}{{ version }}\n{% endfor %}"
    dest: "{{ '~/.pyenv/version' }}"
  tags: pyenv

- name: Install pipx
  tags: pipx
  homebrew: name=pipx state=present
  when: ansible_os_family == "Darwin"

# A global `virtualenv` command is needed for prezto's pyenv-virtualenv to work
- name: Install virtualenv
  shell: "PYENV_VERSION=system python3 -m pip install virtualenv"
  args:
    creates: "/usr/local/bin/virtualenv"
  when: ansible_os_family == "Darwin"
